name: CICD

on: 
  workflow_dispatch:

# 4 Jobs: code / build / test /deploy
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Clone the code"
    
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Build using docker"
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Running the test cases
        run: echo "Run the test cases"
        
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on the machine
        run: echo "Deploying the code"
  
