# Goal - Whenever someone change the paython code, then linter will check syntax, spelling and intentation

name: Auto Linter Check
on:
  push:   # Workflow should be run when someone push or make changes in python file
    paths: "*.py"  

# Job - Code linting  ## 1. First clone the code 2. Install the linter 3. Run the linter
jobs:    
  code-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone/Checkout the code from the github
        uses: actions/checkout@v7   # git hub action to clone the code

      - name: Install the linter
        run: pip install ruff     # Install the linter

      - name: Check the code using linter
        run: ruff check . --fix              # check the syntax

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12' # Specify your required Python version
